---
version: "3"
services:
  motionui:
    container_name: motionui
    image: motionui-image
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        env: prod
        fqdn: motionui.example.com
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/docker/volumes/motionui-data:/var/lib/motionui
      - /var/lib/docker/volumes/motionui-captures:/var/lib/motion
